index:
    path: /
    controller: App\Controller\HomeController::index
results:
    path: /search
    controller: App\Controller\SearchController::index
more_results: 
    path: /more_results
    controller: App\Controller\DiggerController::getMore
    methods: [POST]
    options:
        expose: true