index:
    path: /
    controller: App\Controller\GetHomeController
    methods: [GET]
results:
    path: /search
    controller: App\Controller\GetSearchController
    methods: [GET, POST]
more_results: 
    path: /more_results
    controller: App\Controller\GetMoreResultsController
    methods: [POST]
    options:
        expose: true